name: Movies API CI

on:
  push:
    branches: [ master, staging, develop ]
  pull_request:
    branches: [ master, staging, develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      ALLOWED_HOSTS: ['127.0.0.1',]
      SECRET_KEY: gh-action-insecure-l^5$9ard(^-h0m+(^rw(58u#2p3(7s*yk6r2#+eiutn^%p)m%@
      DJANGO_SETTINGS_MODULE: movies.settings.gh-actions
    

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
